export const NIGIRIMENU = [
	{
		id: 0,
		name: "MAGURO",
		image: "./src/assets/images/maguro.jpeg",
		featured: false,
		description: "Tuna",
		price: 5,
	},
	{
		id: 1,
		name: "TORO SALMON",
		image: "/assets/images/torosalmon.jpg",
		featured: false,
		description: "Fatty salmon sushi",
		price: 5,
	},
	{
		id: 2,
		name: "TAMAGO",
		image: "/assets/images/tamago.jpeg",
		featured: false,
		description: "Cooked egg sushi.",
		price: 3,
	},
	{
		id: 3,
		name: "IKURA",
		image: "/assets/images/ikura.jpeg",
		featured: false,
		description: "Salmon roe.",
		price: 8,
	},
	{
		id: 4,
		name: "AJI",
		image: "/assets/images/aji.jpg",
		featured: false,
		description: "Spanish mackarel",
		price: 5,
	},
];
