export const SIDEMENU = [
	{
		id: 0,
		name: "Assorted Tempura",
		image: "/assets/images/tempura.jpg",
		featured: false,
		description: "Tempura shrimp, shiso, mushroom and eggplant",
		price: 10,
	},
	{
		id: 1,
		name: "Miso soup",
		image: "/assets/images/misosoup.jpg",
		featured: false,
		description: "Miso soup that goes well with your sushi.",
		price: 5,
	},
	{
		id: 2,
		name: "Chawan-mushi",
		image: "/assets/images/chawanmushi.jpg",
		featured: false,
		description: "Cooked egg sushi.",
		price: 5,
	},
	{
		id: 3,
		name: "Matcha Ice cream",
		image: "/assets/images/matchaice.jpg",
		featured: false,
		description: "Green tea ice cream.",
		price: 5,
	},
	{
		id: 4,
		name: "Hot Sake",
		image: "/assets/images/sake.jpg",
		featured: false,
		description: "Hot Sake.",
		price: 5,
	},
];
